services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: lancamento_db
      POSTGRES_USER: lancamento_user
      POSTGRES_PASSWORD: lancamento_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    environment:
      DB_URL: jdbc:postgresql://db:5432/lancamento_db
      DB_USER: lancamento_user
      DB_PASSWORD: lancamento_pass
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:

